# Generated by Django 4.2 on 2023-06-17 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ticket_is_cancelled_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='journey_time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 17, 19, 8, 31, 492484, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
